# -*- coding: utf-8 -*-
"""HR Analytics: Job Change of Data Scientists.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a4moWfKkuc5f7NSFZLMs03XQU8o9-Ts7

### **Introduction**

#### **Context and Content**

A company which is active in Big Data and Data Science wants to hire data scientists among people who successfully pass some courses which conduct by the company.

Many people signup for their training. Company wants to know which of these candidates are really wants to work for the company after training or looking for a new employment because **it helps to reduce the cost and time as well as the quality of training or planning the courses and categorization of candidates**.

Information related to demographics, education, experience are in hands from candidates signup and enrollment.

### **Data Sources**
"""

import pandas as pd

from google.colab import drive
drive.mount('/content/drive')

Work_experience =

"""###1. Enrollies' data

#### Load data
"""

# Reading the Excel File
df_enrollies = pd.read_excel('/content/drive/MyDrive/Enrollies.xlsx')

"""#### Data profiling"""

# Getting DataFrame Info
df_enrollies.info()

"""#### 🧹 Data cleaning: Handling missing values"""

# Filling Missing Values in the gender Column
df_enrollies['gender'] = df_enrollies['gender'].fillna("other").str.lower()

# Getting DataFrame Info Again
df_enrollies.info()

"""###2. Enrollies education

#### Load data
"""

# Reading the Excel File
df_enrollies_education = pd.read_excel('/content/drive/MyDrive/enrollies_education.xlsx')

"""#### Data profiling"""

# Getting DataFrame Info
df_enrollies_education.info()

"""#### 🧹 Data cleaning: Handling missing values"""

# Filling Missing Values in the enrolled_university column by mode() function
df_enrollies_education['enrolled_university'] = df_enrollies_education['enrolled_university'].fillna(df_enrollies_education['enrolled_university'].mode()[0])

# Filling Missing Values in the education_level column by mode() function
df_enrollies_education['education_level'] = df_enrollies_education['education_level'].fillna(df_enrollies_education['education_level'].mode()[0])

# Filling Missing Values in the major_discipline column with the string 'unknown'
df_enrollies_education['major_discipline'] = df_enrollies_education['major_discipline'].fillna('unknown')

# Getting DataFrame Info Again
df_enrollies_education.info()

"""###3. Enrollies' working experience

#### Load data
"""

# Reading the Csv File
df_work_experience = pd.read_csv('/content/drive/MyDrive/work_experience.csv')

"""#### Data profiling"""

# Getting DataFrame Info
df_work_experience.info()

"""#### 🧹 Data cleaning: Handling missing values"""

# Filling Missing Values in the experience column by mode() function
df_work_experience['experience'] = df_work_experience['experience'].fillna(df_work_experience['experience'].mode()[0])

# Filling Missing Values in the company_size column with the string 'unknown'
df_work_experience['company_size'] = df_work_experience['company_size'].fillna('unknown')

# Filling Missing Values in the company_type column with the string 'unknown'
df_work_experience['company_type'] = df_work_experience['company_type'].fillna('unknown')

# Filling Missing Values in the last_new_job column with the string 'unknown'
df_work_experience['last_new_job'] = df_work_experience['last_new_job'].fillna('unknown')

# Getting DataFrame Info Again
df_work_experience.info()

"""###4. Training hours

#### Load data
"""

# Install pymysql
!pip install pymysql

# Import create_engine from sqlalchemy and pymysql
from sqlalchemy import create_engine
import pymysql

# Create a connection to the MySQL database
engine = create_engine('mysql+pymysql://etl_practice:550814@112.213.86.31:3360/company_course')

# Read the table 'training_hours' from the MySQL database into a pandas DataFrame
df_training_hours = pd.read_sql_table('training_hours', con=engine)

"""#### Data profiling"""

# Getting DataFrame Info
df_training_hours.info()

"""###5. City development index

#### Load data
"""

# Read the HTML Table from the URL
df_city_dev = pd.read_html("https://sca-programming-school.github.io/city_development_index/index.html")

# Select the First Table
df_city_dev_table = df_city_dev[0]

"""#### Data profiling"""

# Getting DataFrame Info
df_city_dev_table.info()

"""###6. Employment

#### Load data
"""

# Create a connection to the MySQL database
engine = create_engine('mysql+pymysql://etl_practice:550814@112.213.86.31:3360/company_course')

# Read the table 'training_hours' from the MySQL database into a pandas DataFrame
df_employment = pd.read_sql_table('employment', con=engine)

"""#### Data profiling"""

# Getting DataFrame Info
df_employment.info()